### Register Peserta Magang
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "namaLengkap": "Kesya Sakha arimawanasa",
  "tglLahir": "2002-21-12",
  "email": "sakha12@gmail.com",
  "password": "password123",
  "noTelepon": "081234567890",
  "nik": "3512010102030001",
  "nimNis": "123456789",
  "instansi": "Universitas Negeri Kalimantan",
  "jurusan": "Teknik Informatika",
  "alamat": "Jl. Pahlawan No.10, Sidoarjo",
  "pasFoto": "asda"
}

### Login User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "abiyyiaja@gmail.com",
  "password": "lama12345"
}
